const topics=['systeme','zustandsraum','ruhelage','linearisierung','stabilitaet','steuerbarkeit','regler','beobachtbarkeit','beobachter'];
const names=['Dynamische Systeme','Zustandsraum','Ruhelage','Linearisierung','Stabilität','Steuerbarkeit','Zustandsregler','Beobachtbarkeit','Zustandsbeobachter'];
const saved=JSON.parse(localStorage.getItem('rus-progress')||'{}'),path=document.querySelector('#path');
topics.forEach((t,i)=>path.insertAdjacentHTML('beforeend',`<a href="#${t}" data-path="${t}"><b>${String(i+1).padStart(2,'0')}</b>${names[i]}</a>`));
function progress(){const n=topics.filter(t=>saved[t]).length,p=Math.round(n/topics.length*100);percent.textContent=p+' %';bar.style.width=p+'%';topics.forEach(t=>{document.querySelector(`[data-topic="${t}"]`).classList.toggle('complete',!!saved[t]);document.querySelector(`[data-path="${t}"]`).classList.toggle('complete',!!saved[t])})}
document.querySelectorAll('.done').forEach(b=>{if(saved[b.dataset.topic])b.textContent='Verstanden ✓';b.onclick=()=>{saved[b.dataset.topic]=!saved[b.dataset.topic];localStorage.setItem('rus-progress',JSON.stringify(saved));b.textContent=saved[b.dataset.topic]?'Verstanden ✓':'Als verstanden markieren';progress()}});progress();
menu.onclick=()=>document.querySelector('aside').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('aside').classList.remove('open'));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-25% 0px -65%'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));
document.querySelectorAll('.quiz').forEach(q=>q.querySelectorAll('button').forEach(b=>b.onclick=()=>{q.querySelectorAll('button').forEach(x=>x.className='');const ok=b.dataset.choice===q.dataset.answer;b.className=ok?'correct':'wrong';q.querySelector('p').textContent=ok?'Richtig: x₂ ist die erste Ableitung von x₁; seine Ableitung liefert die zweite Ableitung.':'Noch nicht. Das Ziel sind ausschließlich Gleichungen erster Ordnung.'}));

const exercises=[
['Systeme','Tankmodell','Ein Tank hat Zufluss q und Abfluss k√h. Wähle Zustand, Eingang und Zustandsgleichung.','Der Füllstand speichert die Vergangenheit.','x=h, u=q.','Mit Querschnitt S gilt: S·ḣ=q-k√h, also ḣ=(q-k√h)/S.'],
['Ruhelage','Arbeitspunkt','Bestimme u_R für ẋ=-3x+2u bei x_R=4.','Setze ẋ=0.','u_R=6.','0=-3·4+2u_R ⇒ 12=2u_R ⇒ u_R=6.'],
['Linearisierung','Jacobi-Matrix','Linearisiere ẋ=x²+u um x_R=2.','A ist ∂f/∂x am Arbeitspunkt.','A=4, B=1.','∂f/∂x=2x ⇒ A=4. ∂f/∂u=1 ⇒ B=1. Somit Δẋ=4Δx+Δu.'],
['Stabilität','Pole lesen','Ist ein System mit Polen -2 und 0.5 stabil?','Prüfe alle Realteile.','Instabil.','Der Pol 0.5 erzeugt e^(0.5t) und wächst. Ein positiver Realteil genügt für Instabilität.'],
['Steuerbarkeit','R-Matrix','Prüfe A=[[1,0],[0,2]], b=[1,0]ᵀ.','Berechne Ab und det(R).','Nicht vollständig steuerbar.','Ab=[1,0]ᵀ. R=[[1,1],[0,0]] hat Rang 1. Der zweite Zustand ist nicht erreichbar.'],
['Beobachtbarkeit','O-Matrix','Prüfe A=[[0,1],[0,0]], C=[1,0].','Berechne CA.','Vollständig beobachtbar.','CA=[0,1]. O ist die Einheitsmatrix und hat Rang 2.'],
['Regler','Polvorgabe','Welche Voraussetzung braucht die freie Polvorgabe?','Denke an die R-Matrix.','Vollständige Steuerbarkeit.','Nur bei Rang(R)=n kann der Eingang alle Moden beeinflussen und die Pole frei verschieben.'],
['Beobachter','Fehlerdynamik','Welche Matrix bestimmt den Schätzfehler?','Bilde e=x-x̂.','A-lC.','Subtraktion von Beobachter- und Systemgleichung liefert ė=(A-lC)e.']
];
exercises.forEach((e,i)=>exerciseGrid.insertAdjacentHTML('beforeend',`<article class="exercise-card"><span class="tag">${e[0]}</span><h3>${e[1]}</h3><p>${e[2]}</p><div class="reveal-buttons"><button data-show="h${i}">Tipp</button><button data-show="r${i}">Ergebnis</button><button data-show="s${i}">Rechenweg</button></div><div id="h${i}" class="reveal">${e[3]}</div><div id="r${i}" class="reveal"><b>${e[4]}</b></div><div id="s${i}" class="reveal">${e[5]}</div></article>`));
document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.show).classList.toggle('show'));

const terms={Zustand:'Interne Größe, die zusammen mit dem Eingang die zukünftige Entwicklung festlegt.',Eingang:'Von außen wirkende oder steuerbare Größe u.',Ausgang:'Messbare oder interessierende Größe y.','Systemmatrix A':'Beschreibt die Eigendynamik eines linearen Systems.','Eingangsmatrix B/b':'Beschreibt, wie Eingänge auf Zustände wirken.','Ausgangsmatrix C/cᵀ':'Beschreibt, wie Zustände im Ausgang erscheinen.','Durchgriff D/d':'Unmittelbarer Einfluss von u auf y.',Ruhelage:'Zustand, in dem ẋ=0 gilt.',Arbeitspunkt:'Paar aus Ruhezustand x_R und passendem Eingang u_R.',Linearisierung:'Lokale Tangentennäherung eines nichtlinearen Systems.','Jacobi-Matrix':'Matrix aller ersten partiellen Ableitungen.','Eigenwert':'Kennzahl einer Dynamikmode; der Realteil entscheidet über Wachstum oder Abklingen.','Charakteristisches Polynom':'Polynom det(λI-A), dessen Nullstellen die Eigenwerte sind.','Asymptotisch stabil':'Alle Bewegungen kehren mit der Zeit zur Ruhelage zurück.',Instabil:'Mindestens eine Bewegung entfernt sich von der Ruhelage.',Steuerbarkeit:'Alle Zustände können mit dem Eingang beeinflusst werden.',Beobachtbarkeit:'Alle Zustände können aus dem Ausgang rekonstruiert werden.','Zustandsrückführung':'Regelgesetz, das den Zustand zurückführt.','Ackermann-Formel':'Formel zur Polvorgabe bei steuerbaren Eingrößensystemen.',Beobachter:'Dynamisches Modell, das nicht gemessene Zustände schätzt.',Fehlerdynamik:'Dynamik des Unterschieds e=x-x̂.'};
function renderGloss(q=''){glossary.innerHTML='';Object.entries(terms).filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())).forEach(([k,v])=>glossary.insertAdjacentHTML('beforeend',`<div class="term"><b>${k}</b><p>${v}</p></div>`))}renderGloss();search.oninput=e=>renderGloss(e.target.value);

let calc='eigen';function matrixHTML(id,n,values){return `<div><b>${id}</b><div class="matrix c${n}">${values.map((v,i)=>`<input type="number" step="any" id="${id}${i}" value="${v}">`).join('')}</div></div>`}function vals(id,n){return Array.from({length:n},(_,i)=>+(document.querySelector('#'+id+i).value||0))}function f(x){return Math.abs(x)<1e-10?0:+x.toFixed(4)}
function draw(){let h=matrixHTML('A',2,[0,1,-2,-3]);if(calc==='control')h+=matrixHTML('b',1,[0,1]);if(calc==='observe')h+=matrixHTML('C',2,[1,0]);if(calc==='det3')h=matrixHTML('A',3,[1,2,3,0,1,4,5,6,0]);matrixInputs.innerHTML=`<div class="matrix-form">${h}</div>`;calcResult.innerHTML='<p>Bereit für deine Werte.</p>'}draw();
document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-calc]').forEach(x=>x.classList.remove('active'));b.classList.add('active');calc=b.dataset.calc;draw()});
calculate.onclick=()=>{if(calc==='det3'){let a=vals('A',9),d=a[0]*(a[4]*a[8]-a[5]*a[7])-a[1]*(a[3]*a[8]-a[5]*a[6])+a[2]*(a[3]*a[7]-a[4]*a[6]);calcResult.innerHTML=`<div class="step">Entwicklung nach der ersten Zeile</div><div class="step">det(A) = ${a[0]}·(${a[4]}·${a[8]}-${a[5]}·${a[7]}) - ${a[1]}·(${a[3]}·${a[8]}-${a[5]}·${a[6]}) + ${a[2]}·(${a[3]}·${a[7]}-${a[4]}·${a[6]})</div><b>det(A) = ${f(d)}</b>`;return}let a=vals('A',4),tr=a[0]+a[3],det=a[0]*a[3]-a[1]*a[2];if(calc==='eigen'){let disc=tr*tr-4*det,s=Math.sqrt(Math.abs(disc)),l1=disc>=0?f((tr+s)/2):`${f(tr/2)} + ${f(s/2)}i`,l2=disc>=0?f((tr-s)/2):`${f(tr/2)} - ${f(s/2)}i`;calcResult.innerHTML=`<div class="step">det(λI-A) = λ² - (${f(tr)})λ + (${f(det)})</div><div class="step">Diskriminante = ${f(disc)}</div><div class="step">λ₁ = ${l1}, λ₂ = ${l2}</div><b>${tr<0&&det>0?'Asymptotisch stabil':'Nicht asymptotisch stabil'}</b>`}else if(calc==='control'){let b=vals('b',2),ab=[a[0]*b[0]+a[1]*b[1],a[2]*b[0]+a[3]*b[1]],d=b[0]*ab[1]-ab[0]*b[1];calcResult.innerHTML=`<div class="step">b = [${b}]ᵀ</div><div class="step">Ab = [${ab.map(f)}]ᵀ</div><div class="step">R = [[${b[0]}, ${f(ab[0])}], [${b[1]}, ${f(ab[1])}]]</div><div class="step">det(R) = ${f(d)}</div><b>${d?'Vollständig steuerbar':'Nicht vollständig steuerbar'}</b>`}else{let c=vals('C',2),ca=[c[0]*a[0]+c[1]*a[2],c[0]*a[1]+c[1]*a[3]],d=c[0]*ca[1]-c[1]*ca[0];calcResult.innerHTML=`<div class="step">C = [${c}]</div><div class="step">CA = [${ca.map(f)}]</div><div class="step">O = [[${c}], [${ca.map(f)}]]</div><div class="step">det(O) = ${f(d)}</div><b>${d?'Vollständig beobachtbar':'Nicht vollständig beobachtbar'}</b>`}};
